(()=>{
'use strict';
const EXPECTED=29;
const CARGOS=[['presidente','Presidente'],['governador','Governador'],['senador','Senador'],['depFederal','Deputado Federal'],['depEstadual','Deputado Estadual']];
const CARGO_KEYS=CARGOS.map(x=>x[0]);
let token=sessionStorage.getItem('ce_admin_token')||'';
let snapshot={results:{},updatedAt:null,total:0},locations={locais:[]},tseStatus=null,security=null,candidateSnapshot=null,currentCargo='presidente',deferredPrompt=null,reloadTimer=null;
const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const cargoLabel=k=>CARGOS.find(x=>x[0]===k)?.[1]||k;
function authHeaders(){return token?{Authorization:`Bearer ${token}`}:{}}
async function api(url,opts={}){const headers={...(opts.headers||{}),...authHeaders()};const r=await fetch(url,{cache:'no-store',...opts,headers});let j=null;try{j=await r.json()}catch{}if(!r.ok){const e=new Error(j?.error||`HTTP ${r.status}`);e.status=r.status;e.body=j;throw e}return j}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),3000)}
function parseKey(k){const i=k.indexOf(':');return{section:Number(k.slice(0,i)),cargo:k.slice(i+1)}}
function entries(){return Object.entries(snapshot.results||{}).map(([k,p])=>({...parseKey(k),payload:p||{}}))}
function sectionPlace(section){for(const p of locations.locais||[])if((p.secoes||[]).map(Number).includes(Number(section)))return p;return null}
function allSections(){const a=[...new Set((locations.locais||[]).flatMap(p=>(p.secoes||[]).map(Number)))];return a.sort((x,y)=>x-y)}
function statusForPayload(p){const s=String(p?.verificationStatus||'');if(s==='divergent')return'divergent';if(s==='verified'||s==='tse_official')return'verified';return'pending'}
function sectionInfo(section){const rows=entries().filter(r=>r.section===Number(section));const by=new Map(rows.map(r=>[r.cargo,r.payload]));const count=CARGO_KEYS.filter(k=>by.has(k)).length;const divergent=[...by.values()].some(p=>statusForPayload(p)==='divergent');const allVerified=count===CARGO_KEYS.length&&[...by.values()].every(p=>statusForPayload(p)==='verified');const anyPending=[...by.values()].some(p=>statusForPayload(p)==='pending');let state='waiting';if(divergent)state='divergent';else if(count===0)state='waiting';else if(count<CARGO_KEYS.length)state='partial';else if(allVerified)state='verified';else if(anyPending)state='pending';else state='pending';return{section,count,state,by,place:sectionPlace(section)}}
function sectionLabel(state){return({waiting:'Aguardando BU',partial:'BU parcial',pending:'Em conferência',verified:'Conferida',divergent:'Divergência'})[state]||state}
function stats(){const secs=allSections();const infos=secs.map(sectionInfo);const received=infos.filter(x=>x.count>0).length,complete=infos.filter(x=>x.count===CARGO_KEYS.length).length,verified=infos.filter(x=>x.state==='verified').length,divergent=infos.filter(x=>x.state==='divergent').length,pending=infos.filter(x=>x.state==='partial'||x.state==='pending').length,waiting=Math.max(0,EXPECTED-received);return{secs,infos,received,complete,verified,divergent,pending,waiting}}
function fmtTime(iso){if(!iso)return'—';const d=new Date(iso);if(Number.isNaN(d.getTime()))return'—';return d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function aggregateCargo(cargo){const rows=entries().filter(r=>r.cargo===cargo);const map=new Map();let nominal=0,legenda=0,brancos=0,nulos=0;for(const r of rows){const p=r.payload||{};for(const c of p.candidatos||[]){const key=String(c.numero||c.nome||'').trim();if(!key)continue;const old=map.get(key)||{numero:String(c.numero||''),nome:String(c.nome||''),partido:String(c.partido||''),votos:0};if(!old.nome&&c.nome)old.nome=String(c.nome);if(!old.partido&&c.partido)old.partido=String(c.partido);old.votos+=Number(c.votos||0);map.set(key,old);nominal+=Number(c.votos||0)}for(const l of p.legendas||[])legenda+=Number(l.votos||0);brancos+=Number(p.brancos||0);nulos+=Number(p.nulos||0)}return{rows,items:[...map.values()].sort((a,b)=>b.votos-a.votos||String(a.numero).localeCompare(String(b.numero),'pt-BR',{numeric:true})),nominal,legenda,brancos,nulos}}
function renderOverview(){const s=stats(),pct=Math.round(s.received/EXPECTED*100);$('progressPct').textContent=`${pct}%`;$('progressMain').textContent=`${s.received} de ${EXPECTED} seções recebidas`;$('progressSub').textContent=s.received===0?'Aguardando o início da apuração':s.received===EXPECTED?'Todas as seções já enviaram dados':`${s.waiting} seções ainda aguardando`;$('progressBar').style.width=`${pct}%`;$('updatedAt').textContent=fmtTime(snapshot.updatedAt);$('systemPhase').textContent=s.divergent?`${s.divergent} divergência${s.divergent>1?'s':''} exige${s.divergent>1?'m':''} atenção`:s.pending?`${s.pending} seção${s.pending>1?'ões':''} em conferência`:s.received?'Fluxo normal':'Aguardando dados';$('mReceived').textContent=s.received;$('mComplete').textContent=s.complete;$('mVerified').textContent=s.verified;$('mPending').textContent=s.pending;$('mDivergent').textContent=s.divergent;$('mWaiting').textContent=s.waiting;const attention=s.infos.filter(x=>x.state==='divergent'||x.state==='partial'||x.state==='pending').sort((a,b)=>(a.state==='divergent'?-1:1)-(b.state==='divergent'?-1:1)||a.section-b.section);$('attentionCount').textContent=attention.length;$('attentionList').innerHTML=attention.length?attention.slice(0,7).map(x=>`<button class="attention-item ${x.state==='divergent'?'bad':''}" data-section="${x.section}"><span><b>Seção ${String(x.section).padStart(2,'0')}</b><small>${esc(x.place?.nome||'Local não identificado')} · ${x.count}/5 cargos</small></span><span class="status-pill ${x.state}">${sectionLabel(x.state)}</span></button>`).join(''):'<div class="empty">Nenhuma pendência no momento.</div>';bindSectionButtons($('attentionList'));renderTseSummary()}
function renderTseSummary(){if(!tseStatus){$('tseSummary').innerHTML='<b>Integração oficial</b><br>Ainda não foi possível consultar o estado atual.';return}const phase=String(tseStatus.phase||'ativa').replaceAll('_',' ');$('tseSummary').innerHTML=`<b>${esc(phase)}</b><br>${esc(tseStatus.message||'Conector da Justiça Eleitoral disponível para conferência.')}`}
function renderSections(){const filter=$('sectionFilter').value;const infos=stats().infos.filter(x=>filter==='all'||x.state===filter);$('sectionsGrid').innerHTML=infos.length?infos.map(x=>`<button class="section-card" data-section="${x.section}"><span class="sec-number">Seção ${String(x.section).padStart(2,'0')}</span><span class="place-name">${esc(x.place?.nome||'Local não identificado')}</span><span class="status-pill ${x.state}">${sectionLabel(x.state)}</span><span class="cargo-count">${x.count}/5</span></button>`).join(''):'<div class="empty">Nenhuma seção neste filtro.</div>';bindSectionButtons($('sectionsGrid'))}
function renderCargoTabs(){$('cargoTabs').innerHTML=CARGOS.map(([k,l])=>`<button data-cargo="${k}" class="${k===currentCargo?'active':''}">${l}</button>`).join('');$('cargoTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentCargo=b.dataset.cargo;renderCargoTabs();renderCargo()})}
function renderCargo(){const a=aggregateCargo(currentCargo),done=new Set(a.rows.map(r=>r.section)).size;$('cargoTitle').textContent=cargoLabel(currentCargo);$('cargoCoverage').textContent=`${done}/${EXPECTED}`;$('cargoStatus').textContent=done===0?'Aguardando os primeiros boletins':done===EXPECTED?'Todas as seções publicadas':`Resultado parcial · ${done} de ${EXPECTED} seções`;$('cargoNominal').textContent=fmt(a.nominal);$('vLegenda').textContent=fmt(a.legenda);$('vBrancos').textContent=fmt(a.brancos);$('vNulos').textContent=fmt(a.nulos);$('leaders').innerHTML=a.items.length?a.items.map(c=>{const share=a.nominal?c.votos/a.nominal*100:0;return`<div class="leader"><div class="leader-num">${esc(c.numero||'—')}</div><div class="leader-who"><b>${esc(c.nome||`Candidato ${c.numero||''}`)}</b><small>${esc(c.partido||'Partido não informado')}</small></div><div class="leader-votes"><b>${fmt(c.votos)} votos</b><small>${share.toFixed(1).replace('.',',')}%</small></div><div class="leader-bar"><span style="width:${Math.min(100,share)}%"></span></div></div>`}).join(''):'<div class="empty">Aguardando os primeiros boletins deste cargo.</div>'}
function renderPending(){const s=stats();const urgent=s.infos.filter(x=>x.state==='divergent'||x.state==='partial'||x.state==='pending');$('pendingBoard').innerHTML=urgent.length?urgent.map(x=>{const missing=CARGO_KEYS.filter(k=>!x.by.has(k)).map(cargoLabel);const desc=x.state==='divergent'?'Há divergência entre dados locais e a conferência oficial.':x.state==='partial'?`Faltam: ${missing.join(', ')||'cargos'}.`:'Os cinco cargos chegaram, mas a conferência ainda não terminou.';return`<button class="pending-row ${x.state==='divergent'?'bad':'warn'}" data-section="${x.section}"><span><h3>Seção ${String(x.section).padStart(2,'0')} · ${esc(x.place?.nome||'Local')}</h3><p>${esc(desc)}</p></span><span class="status-pill ${x.state}">${sectionLabel(x.state)}</span></button>`}).join(''):'<div class="card empty">Nenhuma pendência identificada.</div>';bindSectionButtons($('pendingBoard'))}
function renderSecurity(){if(!security){$('secEvents').textContent=$('secDenied').textContent=$('secCorrections').textContent=$('secChain').textContent='—';return}$('secEvents').textContent=fmt(security.total||0);$('secDenied').textContent=fmt(security.denied||0);$('secCorrections').textContent=fmt(security.corrections||0);$('secChain').textContent=security.chain?.ok?'OK':'Atenção'}
function renderCandidates(){const snap=candidateSnapshot?.snapshot||candidateSnapshot;const counts=snap?.counts;if(counts){const total=Object.values(counts).reduce((a,b)=>a+Number(b||0),0);$('candidateStatus').innerHTML=`<b>${fmt(total)} candidaturas no snapshot</b><br>Atualizado ${fmtTime(snap.generatedAt||snap.storedAt)}`}else $('candidateStatus').textContent='Catálogo disponível; detalhes de contagem ainda não carregados.'}
function renderEvents(items=[]){$('recentEvents').innerHTML=items.length?items.slice(0,30).map(e=>`<div class="event-row"><span class="event-badge">${esc(e.outcome||'evento')}</span><span><b>${esc(String(e.event||'evento').replaceAll('_',' '))}</b>${e.section?` · Seção ${e.section}`:''}</span><time>${fmtTime(e.createdAt)}</time></div>`).join(''):'<div class="empty">Nenhum evento recente.</div>'}
function renderAll(){renderOverview();renderSections();renderCargoTabs();renderCargo();renderPending();renderSecurity();renderCandidates()}
function bindSectionButtons(root){root.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>openSection(Number(b.dataset.section)))}
function openSection(section){const x=sectionInfo(section);$('modalBody').innerHTML=`<span class="kicker">DETALHE DA SEÇÃO</span><h2 id="modalTitle">Seção ${String(section).padStart(2,'0')}</h2><p class="muted">${esc(x.place?.nome||'Local não identificado')} · ${esc(x.place?.endereco||'')}</p><span class="status-pill ${x.state}">${sectionLabel(x.state)} · ${x.count}/5 cargos</span><div class="modal-cargos">${CARGOS.map(([k,l])=>{const p=x.by.get(k);const st=p?statusForPayload(p):'waiting';const label=p?(st==='verified'?'Conferido/oficial':st==='divergent'?'Divergência':'Prévia local'):'Aguardando';return`<div class="modal-cargo"><b>${l}</b><span class="status-pill ${st}">${label}</span></div>`}).join('')}</div><div class="modal-actions"><a class="btn" href="/operacao.html?section=${section}">Abrir área operacional</a><button class="btn ghost-dark" data-close-modal>Fechar</button></div>`;$('sectionModal').hidden=false;document.body.style.overflow='hidden';$('modalBody').querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=closeModal)}
function closeModal(){$('sectionModal').hidden=true;document.body.style.overflow=''}
async function loadData(){try{const [s,l,t,sec,cand,events]=await Promise.all([fetch('/api/snapshot',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('snapshot'))),fetch('/data/locais-colmeia.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('locais'))),fetch('/api/tse/status',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),api('/api/admin/security-summary?hours=24').catch(()=>null),fetch('/api/candidates',{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null),api('/api/admin/security-events?limit=30').catch(()=>null)]);snapshot=s;locations=l;tseStatus=t;security=sec;candidateSnapshot=cand;renderAll();renderEvents(events?.items||[]);$('liveDot').className='live-dot ok';$('liveText').textContent='Central ao vivo · conectada'}catch(e){$('liveDot').className='live-dot bad';$('liveText').textContent='Falha ao atualizar';if(e.status===401||e.status===403){logout(false);toast('A sessão administrativa expirou ou não é válida.')}else toast('Não foi possível atualizar todos os dados agora.')}}
function scheduleLoad(){clearTimeout(reloadTimer);reloadTimer=setTimeout(loadData,400)}
async function login(key){token=String(key||'').trim();if(!token)throw new Error('Informe a chave administrativa.');const who=await api('/api/whoami');if(who?.user?.role!=='admin')throw new Error('Esta chave não possui acesso administrativo.');sessionStorage.setItem('ce_admin_token',token);$('sessionUser').textContent=`· ${who.user.name||'Coordenação'}`;$('loginGate').style.display='none';$('app').hidden=false;await loadData();setupStream()}
function logout(show=true){sessionStorage.removeItem('ce_admin_token');token='';try{window._adminES?.close()}catch{};$('app').hidden=true;$('loginGate').style.display='grid';$('adminKey').value='';if(show)toast('Sessão encerrada.')}
function setupStream(){try{window._adminES?.close()}catch{};try{const es=new EventSource('/api/stream');window._adminES=es;es.addEventListener('hello',()=>{$('liveDot').className='live-dot ok';$('liveText').textContent='Central ao vivo · conectada'});es.addEventListener('update',scheduleLoad);es.addEventListener('delete',scheduleLoad);es.onerror=()=>{$('liveDot').className='live-dot';$('liveText').textContent='Reconectando…'}}catch{setInterval(loadData,30000)}}
async function postAction(url,ok){try{const j=await api(url,{method:'POST'});toast(ok);await loadData();return j}catch(e){toast(e.status===403?'Ação exige acesso administrativo.':'Não foi possível concluir a ação.')}}
async function exportData(){try{const data=await api('/api/admin/export');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`central-eleitoral-admin-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Exportação preparada.')}catch{toast('Não foi possível exportar agora.')}}
function setupInstall(){if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});window.addEventListener('appinstalled',()=>{deferredPrompt=null;toast('Central Administrativa instalada.')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('A instalação nativa ficará disponível assim que o navegador liberar o aplicativo.')}}
function setupNav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{const t=$(b.dataset.target);if(t)t.scrollIntoView({behavior:'smooth',block:'start'})});const obs=new IntersectionObserver(es=>{const visible=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===visible.target.id))},{rootMargin:'-20% 0px -55% 0px',threshold:[0,.1,.3]});document.querySelectorAll('.panel-section').forEach(s=>obs.observe(s))}
function init(){$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='';try{await login($('adminKey').value)}catch(err){$('loginMsg').textContent=err.message||'Não foi possível entrar.'}};$('logoutBtn').onclick=()=>logout();$('refreshBtn').onclick=loadData;$('sectionFilter').onchange=renderSections;$('tseRefreshBtn').onclick=()=>postAction('/api/tse/refresh','Consulta ao TSE solicitada.');$('candidateRefreshBtn').onclick=()=>postAction('/api/admin/candidates/refresh','Catálogo de candidaturas atualizado.');$('exportBtn').onclick=exportData;document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});setupInstall();setupNav();if(token)login(token).catch(()=>logout(false))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
