(()=>{
'use strict';
const PATHS=new Set(['/','/index.html','/transparencia.html']);
if(!PATHS.has(location.pathname))return;
let deferredPrompt=null;
const STYLE=`
.public-install-card{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:9px 0;padding:11px 13px;border:1px solid #cfe0eb;border-radius:12px;background:#f5fafe;box-shadow:0 1px 3px rgba(15,42,61,.05)}
.public-install-copy{display:flex;align-items:center;gap:10px;min-width:0}.public-install-icon{display:grid;place-items:center;flex:0 0 34px;width:34px;height:34px;border-radius:10px;background:#e5f1f8;color:#174f7a}.public-install-icon svg{width:18px;height:18px;stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.public-install-text{min-width:0}.public-install-text b{display:block;color:#173f5b;font-size:12px;line-height:1.2}.public-install-text span{display:block;margin-top:2px;color:#607483;font-size:10px;line-height:1.35}
.public-install-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;flex:0 0 auto;min-height:38px;border:0;border-radius:9px;background:#175c88;color:#fff;padding:8px 13px;font:inherit;font-size:10.5px;font-weight:800;line-height:1;cursor:pointer;box-shadow:0 1px 2px rgba(15,42,61,.12)}.public-install-btn svg{width:15px;height:15px;stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.public-install-btn:focus-visible{outline:3px solid #f2c94c;outline-offset:2px}.public-install-card[hidden]{display:none!important}
.public-install-toast{position:fixed;left:50%;bottom:76px;z-index:1400;transform:translateX(-50%);width:min(92vw,520px);padding:10px 12px;border-radius:10px;background:#173f5b;color:#fff;font-size:11px;line-height:1.4;text-align:center;box-shadow:0 8px 28px rgba(0,0,0,.2)}
@media(max-width:520px){.public-install-card{align-items:stretch;flex-direction:column;gap:9px}.public-install-btn{width:100%}.public-install-toast{bottom:72px}}
`;
const isStandalone=()=>window.matchMedia?.('(display-mode: standalone)').matches===true||window.navigator.standalone===true;
function ensureStyle(){if(document.getElementById('v135-install-style'))return;const s=document.createElement('style');s.id='v135-install-style';s.textContent=STYLE;document.head.appendChild(s)}
let toastTimer=null;
function toast(message){let el=document.getElementById('v135InstallToast');if(!el){el=document.createElement('div');el.id='v135InstallToast';el.className='public-install-toast';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.appendChild(el)}el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},4200)}
function installCard(){const hero=document.querySelector('.hero.public-main-hero')||document.querySelector('.hero');if(!hero)return null;document.getElementById('v135InstallWrap')?.remove();let card=document.getElementById('v136InstallCard');if(!card){card=document.createElement('section');card.id='v136InstallCard';card.className='public-install-card';card.setAttribute('aria-label','Instalar Central Eleitoral');card.innerHTML='<div class="public-install-copy"><span class="public-install-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 19h14"/></svg></span><div class="public-install-text"><b>Instalar Central Eleitoral</b><span>Adicione à tela inicial e abra como aplicativo.</span></div></div><button type="button" class="public-install-btn" id="v135InstallBtn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 19h14"/></svg><span>Instalar app</span></button>';hero.after(card);card.querySelector('button').addEventListener('click',requestInstall)}else if(card.previousElementSibling!==hero){hero.after(card)}card.hidden=isStandalone();return card.querySelector('#v135InstallBtn')}
async function requestInstall(){if(isStandalone()){toast('O aplicativo já está instalado neste dispositivo.');installCard();return}if(deferredPrompt){const p=deferredPrompt;deferredPrompt=null;try{await p.prompt();const choice=await p.userChoice;if(choice?.outcome==='accepted')toast('Instalação iniciada.');else toast('Instalação cancelada. Você pode tentar novamente quando quiser.')}catch{toast('O navegador não conseguiu abrir a instalação agora. Tente novamente em alguns segundos.')}installCard();return}toast('A instalação direta ainda não foi liberada pelo navegador. Aguarde alguns segundos e toque novamente em “Instalar app”.')}
function refresh(){ensureStyle();installCard()}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;refresh()});
window.addEventListener('appinstalled',()=>{deferredPrompt=null;refresh();toast('Central Eleitoral instalada com sucesso.')});
function boot(){refresh();navigator.serviceWorker?.ready?.then(()=>setTimeout(refresh,250)).catch(()=>{});setTimeout(refresh,300);setTimeout(refresh,1200);let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;refresh()})}).observe(document.body,{childList:true,subtree:true});window.matchMedia?.('(display-mode: standalone)').addEventListener?.('change',refresh);window.addEventListener('pageshow',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
