import fs from 'node:fs';
const pub='/app/public';
const read=p=>fs.readFileSync(p,'utf8');
const write=(p,s)=>fs.writeFileSync(p,s);

const css=`
/* V1.6.1 — identidade regional, candidatos completos e cargos na operação */
:root{--ce-green:#009B3A;--ce-yellow:#FFDF00;--ce-blue:#002776;--ce-to:#2450B2;--ce-col:#9FD0F0;--ce-ink:#17324A;--ce-muted:#687985;--ce-line:#D9E5EB}
.hero,.top{position:relative!important;isolation:isolate!important;overflow:hidden!important;border-top:4px solid var(--ce-yellow)!important;background:linear-gradient(118deg,#008D3D 0%,#009B3A 22%,#137B68 44%,#2450B2 72%,#002776 100%)!important;box-shadow:0 10px 26px rgba(0,39,118,.13)!important}.hero:before,.top:before{display:none!important;content:none!important}.hero:after,.top:after{content:''!important;display:block!important;position:absolute!important;z-index:0!important;left:0!important;right:0!important;bottom:0!important;top:auto!important;width:auto!important;height:4px!important;background:linear-gradient(90deg,var(--ce-green) 0 34%,var(--ce-yellow) 34% 50%,var(--ce-col) 50% 66%,var(--ce-blue) 66% 100%)!important;pointer-events:none!important}.hero>*,.top>*{position:relative!important;z-index:1!important}.hero .eyebrow,.top .eyebrow{color:#FFF3A3!important}.hero h1,.top h1{color:#fff!important}.hero p,.top p{color:rgba(255,255,255,.88)!important}
.metrics .metric:nth-child(4n+1){border-top-color:var(--ce-green)!important}.metrics .metric:nth-child(4n+2){border-top-color:var(--ce-to)!important}.metrics .metric:nth-child(4n+3){border-top-color:var(--ce-yellow)!important}.metrics .metric:nth-child(4n+4){border-top-color:var(--ce-col)!important}.pwa-install-card{background:linear-gradient(135deg,#F0FAF4 0%,#F8FCFF 57%,#FFFCEB 100%)!important;border-top:3px solid var(--ce-green)!important}.pwa-install-btn,.btn.primary,.toolbar .primary,.quick-actions .primary{background:linear-gradient(110deg,#168650 0%,#187B6A 36%,#2450B2 76%,#16459A 100%)!important;color:#fff!important;border-color:transparent!important}.cargo-tabs button.active,#cargoTabs button.active,.nav-tabs button.active,.tab.active{background:linear-gradient(110deg,#13864E,#2450B2)!important;color:#fff!important;border-color:transparent!important}.footer-nav button.active,.bottom-nav button.active,.public-bottom-nav button.active{position:relative!important;background:transparent!important;color:#174F7A!important}.footer-nav button.active:before,.bottom-nav button.active:before,.public-bottom-nav button.active:before{content:''!important;position:absolute!important;left:31%!important;right:31%!important;top:0!important;height:3px!important;border-radius:0 0 99px 99px!important;background:linear-gradient(90deg,var(--ce-green),var(--ce-yellow),var(--ce-blue))!important}.progress span,.progress i,.public-progress i{background:linear-gradient(90deg,var(--ce-green) 0 42%,var(--ce-yellow) 42% 55%,var(--ce-to) 55% 100%)!important}
#leaders .leader{--party:#2450B2;position:relative!important;overflow:visible!important;border-left:5px solid var(--party)!important;background:#fff!important}#leaders .leader .bar{background:#E7EEF2!important}#leaders .leader .bar i{background:var(--party)!important}#leaders .leader .votes small{color:var(--party)!important;font-weight:900!important}#leaders .leader .who small{display:flex!important;align-items:center!important;gap:5px!important}#leaders .leader .who small:before{content:'';display:inline-block;width:7px;height:7px;flex:0 0 7px;border-radius:50%;background:var(--party)}#leaders .leader .public-number-badge{background:var(--party)!important;color:#fff!important}#leaders .leader .num:not(.public-photo-num){background:#F5F9FB!important;color:var(--party)!important;border:1px solid #DCE7EC!important}
.ce161-zero-note{margin:8px 0 10px;padding:9px 11px;border:1px solid #dbe8df;border-radius:10px;background:linear-gradient(135deg,#f3fbf6,#f8fbff 64%,#fffceb);color:#526873;font-size:10px;line-height:1.4}.ce161-zero-note b{color:#1e5941}.ce161-photo-num{position:relative!important;overflow:hidden!important;padding:0!important}.ce161-photo-num img{display:block;width:100%;height:100%;object-fit:cover}.ce161-photo-num .public-number-badge{position:absolute;left:3px;bottom:3px;min-width:22px;padding:2px 4px;border-radius:6px;color:#fff;font-size:8px;font-weight:900;text-align:center;line-height:1.1;box-shadow:0 1px 4px rgba(0,0,0,.16)}
.ce161-rank{position:absolute;right:7px;top:-8px;display:inline-flex;align-items:center;justify-content:center;height:20px;min-width:28px;padding:0 7px;border-radius:999px;background:#F2F6F8;border:1px solid #D5E2E8;color:#49616F;font-size:8.5px;font-weight:900}.leader[data-ce161-rank="1"] .ce161-rank{background:#FFF8D8;border-color:#E8CE60;color:#725500}.ce161-race{margin:9px 0 11px;padding:11px 12px;border:1px solid var(--ce-line);border-radius:12px;background:linear-gradient(135deg,#F8FBFC,#fff 60%,#FFFDF3)}.ce161-race[hidden]{display:none!important}.ce161-race small{display:block;color:#557080;font-size:8.5px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.ce161-race b{display:block;margin-top:3px;color:var(--ce-ink);font-size:12.5px}.ce161-race span{display:block;margin-top:4px;color:#71808A;font-size:9px}
.ce161-op-candidates{margin:12px 0;padding:13px;border:1px solid #d8e5eb;border-radius:15px;background:#fff;box-shadow:0 4px 14px rgba(20,60,90,.055)}.ce161-op-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.ce161-op-kicker{font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#557384}.ce161-op-head h2{margin:3px 0 2px;font-size:16px;color:#17324a}.ce161-op-head p{margin:0;color:#71818a;font-size:10px;line-height:1.35}.ce161-op-count{flex:0 0 auto;padding:5px 8px;border-radius:999px;background:#eef5f8;color:#315b75;font-size:9px;font-weight:850}.ce161-op-tabs{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;margin:10px -2px 8px;padding:2px}.ce161-op-tabs::-webkit-scrollbar{display:none}.ce161-op-tabs button{flex:0 0 auto;border:1px solid #d8e3e8;background:#fff;color:#375769;border-radius:999px;padding:8px 10px;font:inherit;font-size:10px;font-weight:800;cursor:pointer}.ce161-op-tabs button.active{border-color:transparent;background:linear-gradient(110deg,#168650,#2450B2);color:#fff}.ce161-op-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.ce161-op-card{--party:#2450B2;display:grid;grid-template-columns:44px minmax(0,1fr);gap:8px;align-items:center;min-width:0;padding:8px;border:1px solid #e1e8ec;border-left:4px solid var(--party);border-radius:11px;background:#fff}.ce161-op-photo{position:relative;width:44px;height:52px;border-radius:9px;background:#eef3f6;overflow:hidden;display:grid;place-items:center;color:var(--party);font-size:12px;font-weight:900}.ce161-op-photo img{width:100%;height:100%;object-fit:cover}.ce161-op-photo span{position:absolute;left:3px;bottom:3px;padding:2px 4px;border-radius:5px;background:var(--party);color:#fff;font-size:8px;line-height:1;font-weight:900}.ce161-op-info{min-width:0}.ce161-op-info b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#1c3446;font-size:10.5px}.ce161-op-info small{display:block;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#73838d;font-size:8.8px}.ce161-op-empty{padding:14px 8px;text-align:center;color:#71808a;font-size:10px}.ce161-op-help{margin-top:8px;color:#71808a;font-size:9px;line-height:1.35}@media(max-width:420px){.ce161-op-grid{grid-template-columns:1fr}.ce161-op-photo{width:48px;height:56px}}
`;

const js=`(()=>{
'use strict';
const PUBLIC=new Set(['/','/index.html','/transparencia.html']);
const OP=location.pathname==='/operacao.html';
const CARGOS=[['presidente','Presidente'],['governador','Governador'],['senador','Senador'],['depFederal','Deputado Federal'],['depEstadual','Deputado Estadual']];
const COLORS={PT:'#D71920',PL:'#1351A3',MDB:'#178544',PSD:'#2F86C7',PP:'#1B62A9',REPUBLICANOS:'#173D77',PDT:'#C91F2C',PSB:'#E5A800',PODEMOS:'#2BA866',AVANTE:'#F28A22',PSDB:'#1757A6',PCDOB:'#D91D2A',PV:'#1C9C45',REDE:'#28A96B',PSOL:'#F28C00',CIDADANIA:'#E85E24',NOVO:'#F58220',PRD:'#214C8B',SOLIDARIEDADE:'#E66B19',DC:'#1E5F9E',MOBILIZA:'#2B64B1',PCB:'#C5161D',PSTU:'#C61C2B',UP:'#7A1D8F'};
let catalog=null,opCargo='presidente',queued=false;
function norm(v){return String(v||'').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim()}
function partyColor(v){const s=norm(v);if(s.includes('UNIAO BRASIL')||s==='UNIAO')return '#E7B900';for(const k in COLORS)if((' '+s+' ').includes(' '+k+' '))return COLORS[k];return '#2450B2'}
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(m){return m==='&'?'&amp;':m==='<'?'&lt;':m==='>'?'&gt;':'&quot;'})}
function cargoLabel(k){const x=CARGOS.find(x=>x[0]===k);return x?x[1]:k}
function intValue(v){const m=String(v||'').replace(/\\./g,'').match(/-?\\d+/);return m?Number(m[0]):0}
function activeCargo(){const b=document.querySelector('#cargoTabs button.active[data-cargo],.cargo-tabs button.active[data-cargo],[data-cargo].active');if(b&&b.dataset.cargo)return b.dataset.cargo;for(const sel of document.querySelectorAll('select')){const opts=[...sel.options];if(opts.filter(o=>CARGOS.some(x=>norm(o.textContent)===norm(x[1]))).length>=3){const o=sel.options[sel.selectedIndex];const t=norm(o&&o.textContent);for(const x of CARGOS)if(norm(x[1])===t)return x[0]}}const t=norm(document.getElementById('cargoTitle')?.textContent);for(const x of CARGOS)if(norm(x[1])===t)return x[0];return 'presidente'}
function rowsFor(k){const a=catalog&&catalog.candidates&&Array.isArray(catalog.candidates[k])?catalog.candidates[k]:[];return a.slice().sort((a,b)=>String(a.numero||'').localeCompare(String(b.numero||''),'pt-BR',{numeric:true}))}
function rowNumber(row){const badge=row.querySelector('.public-number-badge');if(badge)return String(badge.textContent||'').trim();return String(row.querySelector('.num')?.textContent||'').replace(/\\D/g,'')}
function photoBox(c){const n=esc(c.numero||'—'),p=partyColor(c.partido),f=esc(c.foto||'');if(!f)return '<div class="num" style="--party:'+p+'">'+n+'</div>';return '<div class="num public-photo-num ce161-photo-num" style="--party:'+p+'"><img class="public-candidate-photo" src="'+f+'" alt="Foto de '+esc(c.nome||'candidato')+'" loading="lazy" decoding="async"><span class="public-number-badge">'+n+'</span></div>'}
function zeroRow(c){const p=partyColor(c.partido);return '<div class="leader ce161-catalog-zero" data-ce161-number="'+esc(c.numero||'')+'" style="--party:'+p+'">'+photoBox(c)+'<div class="who"><b>'+esc(c.nome||('Candidato '+(c.numero||'')))+'</b><small>'+esc(c.partido||'Partido não informado')+'</small></div><div class="votes"><b>0</b><small>0,0%</small></div><div class="bar"><i style="width:0%;background:'+p+'"></i></div></div>'}
function hydrate(row,c){if(!c)return;row.style.setProperty('--party',partyColor(c.partido));const who=row.querySelector('.who'),b=who?.querySelector('b'),s=who?.querySelector('small');if(b&&(/^Candidato\\s/i.test(b.textContent)||!b.textContent.trim())&&c.nome)b.textContent=c.nome;if(s&&(!s.textContent.trim()||/não informado/i.test(s.textContent))&&c.partido)s.textContent=c.partido;const box=row.querySelector('.num');if(box&&c.foto&&!box.querySelector('img')){const n=rowNumber(row)||String(c.numero||'');box.classList.add('public-photo-num','ce161-photo-num');box.textContent='';const img=document.createElement('img');img.className='public-candidate-photo';img.src=c.foto;img.alt='Foto de '+(c.nome||'candidato');img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>img.remove(),{once:true});const badge=document.createElement('span');badge.className='public-number-badge';badge.textContent=n;box.append(img,badge)}}
function ensurePublic(){if(!PUBLIC.has(location.pathname)||!catalog)return;const leaders=document.getElementById('leaders');if(!leaders)return;const cargo=activeCargo(),all=rowsFor(cargo);if(!all.length)return;const existing=[...leaders.querySelectorAll('.leader')],byNum=new Map(all.map(c=>[String(c.numero||''),c])),seen=new Set();existing.forEach(r=>{const n=rowNumber(r)||String(r.dataset.ce161Number||'');if(n){seen.add(n);hydrate(r,byNum.get(n))}});const missing=all.filter(c=>!seen.has(String(c.numero||'')));if(!existing.length)leaders.innerHTML=all.map(zeroRow).join('');else if(missing.length)leaders.insertAdjacentHTML('beforeend',missing.map(zeroRow).join(''));wireImages(leaders);const hasVotes=[...leaders.querySelectorAll('.votes b')].some(el=>intValue(el.textContent)>0);let note=document.getElementById('ce161ZeroNote');if(!hasVotes){if(!note){note=document.createElement('div');note.id='ce161ZeroNote';note.className='ce161-zero-note';leaders.before(note)}note.innerHTML='<b>Apuração ainda não iniciada para '+esc(cargoLabel(cargo))+'.</b> Os candidatos já aparecem abaixo com foto, nome, número e 0 votos.'}else if(note)note.remove();decorate(leaders)}
function wireImages(root){root.querySelectorAll('img.public-candidate-photo:not([data-ce161-img])').forEach(img=>{img.dataset.ce161Img='1';img.addEventListener('error',()=>img.remove(),{once:true})})}
function decorate(leaders){const rows=[...leaders.querySelectorAll('.leader')];rows.forEach(r=>{const p=r.querySelector('.who small')?.textContent||'';r.style.setProperty('--party',partyColor(p));r.querySelector('.ce161-rank')?.remove();r.removeAttribute('data-ce161-rank')});const positive=rows.map(r=>({r,v:intValue(r.querySelector('.votes b')?.textContent),name:r.querySelector('.who b')?.textContent||'Candidato'})).filter(x=>x.v>0);const sig=positive.map(x=>x.name+':'+x.v).join('|');if(leaders.dataset.ce161RankSig===sig)return;leaders.dataset.ce161RankSig=sig;positive.slice(0,3).forEach((x,i)=>{x.r.dataset.ce161Rank=String(i+1);const s=document.createElement('span');s.className='ce161-rank';s.textContent=(i+1)+'º';x.r.appendChild(s)});let race=document.getElementById('ce161Race');if(positive.length<2){if(race)race.hidden=true;return}if(!race){race=document.createElement('div');race.id='ce161Race';race.className='ce161-race';leaders.before(race)}const a=positive[0],b=positive[1],gap=Math.max(0,a.v-b.v);race.hidden=false;race.innerHTML='<small>Leitura da disputa</small><b>'+esc(a.name)+' está à frente neste momento</b><span>'+gap.toLocaleString('pt-BR')+' votos de diferença para o 2º colocado · resultado parcial.</span>'}
function opHost(){let box=document.getElementById('ce161OperatorCandidates');const anchor=document.getElementById('candidateCatalog')||document.querySelector('[data-candidate-catalog],.candidate-catalog');if(!box){box=document.createElement('section');box.id='ce161OperatorCandidates';box.className='ce161-op-candidates';if(anchor)anchor.before(box);else (document.querySelector('main,.wrap,.container')||document.body).appendChild(box)}return box}
function syncNativeCargo(key){const target=norm(cargoLabel(key));for(const sel of document.querySelectorAll('select')){const opts=[...sel.options];if(opts.filter(o=>CARGOS.some(x=>norm(o.textContent)===norm(x[1]))).length>=3){const opt=opts.find(o=>norm(o.textContent)===target||norm(o.value)===norm(key));if(opt){sel.value=opt.value;sel.dispatchEvent(new Event('input',{bubbles:true}));sel.dispatchEvent(new Event('change',{bubbles:true}));return true}}}const btn=[...document.querySelectorAll('button,[role="tab"],[data-cargo]')].find(b=>!b.closest('#ce161OperatorCandidates')&&(norm(b.dataset?.cargo)===norm(key)||norm(b.textContent)===target));if(btn){btn.click();return true}return false}
function opCard(c){const p=partyColor(c.partido),f=esc(c.foto||''),n=esc(c.numero||'—');return '<div class="ce161-op-card" style="--party:'+p+'"><div class="ce161-op-photo">'+(f?'<img src="'+f+'" alt="Foto de '+esc(c.nome||'candidato')+'" loading="lazy">':'')+'<span>'+n+'</span></div><div class="ce161-op-info"><b>'+esc(c.nome||('Candidato '+(c.numero||'')))+'</b><small>'+n+' · '+esc(c.partido||'Partido não informado')+'</small></div></div>'}
function renderOp(){if(!OP||!catalog)return;const box=opHost(),rows=rowsFor(opCargo),sig=opCargo+'|'+rows.length+'|'+String(catalog.generatedAt||catalog.updatedAt||'');if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML='<div class="ce161-op-head"><div><div class="ce161-op-kicker">Consulta de candidaturas</div><h2>Candidatos por cargo</h2><p>Escolha qualquer um dos cinco cargos para ver os candidatos.</p></div><span class="ce161-op-count">'+rows.length+' candidatos</span></div><div class="ce161-op-tabs" role="tablist">'+CARGOS.map(x=>'<button type="button" data-ce161-cargo="'+x[0]+'" class="'+(x[0]===opCargo?'active':'')+'">'+x[1]+'</button>').join('')+'</div><div class="ce161-op-grid">'+(rows.length?rows.map(opCard).join(''):'<div class="ce161-op-empty">Nenhuma candidatura disponível para este cargo.</div>')+'</div><div class="ce161-op-help">A consulta não altera votos nem envia BU. Se houver seletor nativo de cargo, ele é sincronizado automaticamente.</div>';wireImages(box);box.querySelectorAll('[data-ce161-cargo]').forEach(b=>b.onclick=()=>{opCargo=b.dataset.ce161Cargo||'presidente';syncNativeCargo(opCargo);box.dataset.sig='';renderOp()})}
function extract(j){if(j&&j.available&&j.snapshot)return j.snapshot;if(j&&j.snapshot&&j.snapshot.candidates)return j.snapshot;if(j&&j.candidates)return j;return null}
async function loadCatalog(){let got=null;try{const r=await fetch('/api/candidates',{cache:'no-store'});if(r.ok)got=extract(await r.json())}catch{}if(!got){try{const r=await fetch('/data/candidate-catalog.json',{cache:'no-store'});if(r.ok)got=extract(await r.json())}catch{}}if(got){catalog=got;run()}}
function apply(){document.documentElement.dataset.ceUi='161';ensurePublic();renderOp()}
function run(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}
function start(){loadCatalog();run();setTimeout(run,250);setTimeout(run,900);setTimeout(run,1600);new MutationObserver(run).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',()=>setTimeout(run,80),true);window.addEventListener('pageshow',()=>{loadCatalog();run()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();`;

write(`${pub}/v157-polish.css`,css);
write(`${pub}/v157-polish.js`,js);
for(const file of [`${pub}/index.html`,`${pub}/transparencia.html`,`${pub}/operacao.html`]){
  let html=read(file);
  html=html.replace(/\/v157-polish\.css\?v=\d+/g,'/v157-polish.css?v=161').replace(/\/v157-polish\.js\?v=\d+/g,'/v157-polish.js?v=161');
  if(!html.includes('/v157-polish.css'))html=html.replace('</head>','<link rel="stylesheet" href="/v157-polish.css?v=161">\n</head>');
  if(!html.includes('/v157-polish.js'))html=html.replace('</body>','<script src="/v157-polish.js?v=161"></script>\n</body>');
  write(file,html);
}
let sw=read(`${pub}/service-worker.js`);
sw=sw.replace(/const VERSION='[^']+';/,"const VERSION='v1.5.7-unified';");
if(!sw.includes("'/v157-polish.css'"))sw=sw.replace(/(const CORE=\[[\s\S]*?)(\];)/,(m,a,b)=>a+",'/v157-polish.css','/v157-polish.js'"+b);
write(`${pub}/service-worker.js`,sw);
console.log('V1.6.1 interface applied: public candidates remain visible at zero and operation supports all five cargos.');