(()=>{'use strict';
const CARGOS=['presidente','governador','senador','depFederal','depEstadual'];
let catalog=null,queued=false;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
function displayName(c){return String(c?.nomeUrna||c?.nome||'').trim()}
function activeCargo(){const b=document.querySelector('#cargoTabs button.active[data-cargo],.cargo-tabs button.active[data-cargo],[data-cargo].active');if(b?.dataset?.cargo)return b.dataset.cargo;const t=norm(document.querySelector('#cargoTitle,.results-head h2,.results-head h3')?.textContent);if(t.includes('GOVERNADOR'))return'governador';if(t.includes('SENADOR'))return'senador';if(t.includes('DEPUTADO FEDERAL'))return'depFederal';if(t.includes('DEPUTADO ESTADUAL'))return'depEstadual';return'presidente'}
function rowNumber(row){return String(row.dataset.ce161Number||row.querySelector('.ce162-number-text')?.textContent||row.querySelector('.public-number-badge')?.textContent||row.querySelector('.num')?.textContent||'').match(/\d{1,5}/)?.[0]||''}
function findCandidate(cargo,n){const a=catalog?.candidates?.[cargo];return Array.isArray(a)?a.find(c=>String(c.numero||'')===String(n))||null:null}
function statusLabel(c){const g=c?.statusGrupo||'';if(g==='sub_judice')return'Sub judice';if(g==='pendente')return'Pendente de julgamento';if(g==='renuncia')return'Renúncia';if(g==='falecimento')return'Falecimento';if(g==='cancelada')return'Cancelada';if(g==='cassada')return'Cassada';if(g==='indeferida')return'Indeferida';if(g==='nao_conhecida')return'Pedido não conhecido';const s=String(c?.situacao||'').trim();if(!s||/^#(?:NE|NULO)$/i.test(s)||s==='-1'||/deferid/i.test(s))return'';return s}
function ensureStatus(row,c){let el=row.querySelector('.ce187-status');const label=statusLabel(c);if(!label){el?.remove();return}if(!el){el=document.createElement('span');el.className='ce187-status';const who=row.querySelector('.who,.ce161-op-info')||row;who.appendChild(el)}el.textContent=label;el.dataset.kind=c.statusGrupo||'outros';el.dataset.active=String(c.ativo!==false)}
function ensurePhoto(row,c,n){const box=row.querySelector('.num,.ce161-op-photo');if(!box||!c?.foto)return;let img=box.querySelector('img');if(img&&img.getAttribute('src')===c.foto)return;if(!img){img=document.createElement('img');img.className='public-candidate-photo';img.loading='lazy';img.decoding='async';box.prepend(img)}img.alt='Foto de '+(displayName(c)||'candidato');img.onerror=()=>{img.remove();if(box.classList.contains('num'))box.textContent=n||c.numero||'—'};img.src=c.foto}
function hydrateResults(){if(!catalog)return;const cargo=activeCargo();document.querySelectorAll('#leaders .leader').forEach(row=>{const n=rowNumber(row),c=findCandidate(cargo,n);if(!c)return;const b=row.querySelector('.who b');if(b&&displayName(c))b.textContent=displayName(c);row.dataset.ce187Candidate=c.sqCandidato||'';ensurePhoto(row,c,n);ensureStatus(row,c)})}
function adoptCatalog(){if(!catalog)return;try{if(typeof window.CANDIDATOS!=='undefined'){for(const k of CARGOS){const rows=catalog.candidates?.[k];if(!Array.isArray(rows))continue;window.CANDIDATOS[k]=rows.filter(c=>c.ativo!==false||c.subJudice===true).map(c=>({...c,nomeLegal:c.nome,nome:displayName(c)||c.nome}))}if(typeof window.renderCandidates==='function')window.renderCandidates(true)}}catch(e){console.warn('V1.8.7 catálogo visual',e)}}
function removeLiteralEscapes(){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const a=[];while(w.nextNode())a.push(w.currentNode);for(const n of a){if(n.parentElement?.closest('script,style,textarea'))continue;const t=n.nodeValue||'';if(t.includes('\\n'))n.nodeValue=t.replace(/^\s*\\n\s*/,'').replace(/\s*\\n\s*$/,' ')}}
function removeTechTags(){document.querySelectorAll('main span,main small,main em,.candidate-catalog span,.candidate-catalog small').forEach(el=>{if(/^#ne\b/i.test((el.textContent||'').trim())){el.classList.add('ce187-tech-tag');el.setAttribute('aria-hidden','true')}})}
function markCandidateCards(){document.querySelectorAll('.ce161-op-card,.candidate-card,.candidate-row,[data-candidate],#candidateCatalog .card').forEach(el=>el.classList.add('ce187-candidate-card'))}
function fixScrollTop(){document.querySelectorAll('button,a').forEach(el=>{const t=(el.textContent||'').trim();if((t==='↑'||t==='⇧'||/voltar ao topo/i.test(el.getAttribute('aria-label')||''))&&getComputedStyle(el).position==='fixed')el.classList.add('ce187-scrolltop')})}
function fixAdminLabels(){if(!location.pathname.includes('/admin'))return;document.querySelectorAll('.metric,.card').forEach(card=>{const h=norm(card.querySelector('small,.label,.metric-label')?.textContent);const sub=card.querySelector('em,.sub,.metric-sub,p');if(!sub)return;if(h.includes('CONFERIDAS')&&/seções completas/i.test(sub.textContent||''))sub.textContent='validadas pela coordenação';if(h.includes('EM CONFERENCIA')&&/exigem acompanhamento/i.test(sub.textContent||''))sub.textContent='aguardam validação da coordenação'})}
function ensurePreElectionNotice(){
 const PUBLIC=new Set(['/','/index.html','/transparencia.html']);if(!PUBLIC.has(location.pathname))return;
 const cutoff=Date.parse('2026-10-04T17:00:00-03:00'),pre=Date.now()<cutoff;
 document.documentElement.classList.toggle('ce187-pre-election',pre);
 let box=document.getElementById('ce187TestNotice');
 if(!pre){box?.remove();return}
 if(!box){box=document.createElement('aside');box.id='ce187TestNotice';box.className='ce187-test-notice';box.setAttribute('role','status');const hero=document.querySelector('.hero,.public-hero,header');(hero?.parentNode||document.body).insertBefore(box,hero?hero.nextSibling:document.body.firstChild)}
 box.innerHTML='<b>AMBIENTE DE TESTE · DADOS NÃO OFICIAIS</b><span>A eleição ocorre em 4 de outubro de 2026. Votos, percentuais e andamento exibidos nesta Central nesta fase são dados de simulação e não representam resultado eleitoral.</span>';
}
function fixCompletionNote(){const complete=/29\s*\/\s*29|100%/.test(document.body.textContent||'');if(!complete)return;document.querySelectorAll('div,p,span').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(/^Acompanhamento local\s*·\s*resultados parciais podem mudar durante a apuração\.?$/i.test(t))el.textContent='Apuração local concluída · resultados sujeitos à conferência e à totalização oficial da Justiça Eleitoral.'})}
function run(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;removeLiteralEscapes();removeTechTags();markCandidateCards();fixScrollTop();fixAdminLabels();ensurePreElectionNotice();fixCompletionNote();hydrateResults()})}
async function load(){try{const r=await fetch('/data/candidate-catalog.json?v=187',{cache:'no-store'});if(r.ok){catalog=await r.json();adoptCatalog();run()}}catch(e){console.warn('V1.8.7 catálogo estático indisponível',e)}}
function start(){load();run();[150,500,1200,2500].forEach(ms=>setTimeout(run,ms));new MutationObserver(run).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',()=>setTimeout(run,80),true);window.addEventListener('pageshow',()=>{load();run()})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
})();